version: '2.1'

services:
  signalmaster:
    image: signalmaster
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8888:8888
      - 9229:9229
    volumes:
      - .:/usr/src/app
    command: node --inspect server.js